#!/usr/bin/env python3
""" Simple tool for pretty printing JSON to the terminal.

Symlink cause I know you'll end up googling it otherwise:
`ln -s $(pwd)/pprint_json /usr/local/bin`

Alias belongs in your `.bash_profile` - at least if you are on a macbook.
"""

import os
import sys
import json
import pprint

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("     Hey... specify a JSON file!")
        exit()

    file_name = sys.argv[1]
    ext = os.path.splitext(file_name)[-1].lower()
    if ext != '.json':
        print("     I said JSON, not {}!".format(ext))
        exit()

    path = os.path.abspath(file_name)
    with open(path, 'r') as data:
        out = json.load(data)
    print(pprint.pformat(out))
